### ISSUE TITLE
Masonry prepended trigger items

### ISSUE THREAD

**Issue by johnsolarz** [webcreate/infinite-ajax-scroll#143]
Hello! I'm failing to achieve masonry/isotope-loaded items that would logically be prepended to the masonry container rather than appended to it upon clicking the Trigger Extension. Instead, for example, page 2 items are continuously loaded after/below page 3 items rather than before/above, and so on with each trigger. I'm attempting to acquire the trigger, paging and history extension similar to http://infiniteajaxscroll.com/examples/history.html but within a masonry layout. Do you have an example of combining these with masonry.prepended items or is this a limitation of the plugin?

**Comment by Twansparant** [comment]
> The plugin was build with the assumption that items are added below not before

Which plugin, Infinite Ajax Scroll or Isotope? Because in the history demo (http://infiniteajaxscroll.com/examples/history/page3.html) the page 2 items are added before and not below page 3, so Infinite Ajax Scroll can do it.
In Isotope you can also prepend items instead of append, so in my opinion there are no limitations?

**Comment by fieg** [comment]
There are no limitations when you have enough technical skills to script a workaround. Most of IAS users don't have these skills, so with "it's a limitation" I meant it isn't support out of the box.

For an idea of a technical implementation users can check this issue: https://github.com/webcreate/infinite-ajax-scroll/issues/193
