### ISSUE TITLE
Extensions on jsDelivr

### ISSUE THREAD

**Issue by humancopy** [webcreate/infinite-ajax-scroll#163]
Hey :)

Could you please add the extensions to jsDelivr as well?

Thanks ...

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account and v3 is available on jsDelivr:
https://www.jsdelivr.com/package/npm/@webcreate/infinite-ajax-scroll

If you have questions, feedback or think this issue is closed by mistake, please comment on this issue.
