### ISSUE TITLE
IAS does not load new pages when scrolling very fast

### ISSUE THREAD

**Issue by tulanowski** [webcreate/infinite-ajax-scroll#167]
If you are scrolling page very fast 3rd and consecutive pages are not loading. I guess, that this happens if you manage to scroll down completely before 'loaded' (or rendered?) event fire. This problem can be observed here:
http://www.apetytonline.pl/

**Comment by fflewddur** [comment]
I ran into this too. An easy fix is to call scrollHandler() after the 'rendered' event; if the user has scrolled past the end of the items that were being loaded (during which IAS is paused), this causes next() to be called again once IAS resumes. Here's a patch:

diff --git a/src/jquery-ias.js b/src/jquery-ias.js
index 98ac562..e1c0f87 100644
--- a/src/jquery-ias.js
+++ b/src/jquery-ias.js
@@ -537,6 +537,9 @@
           self.nextUrl = self.getNextUrl(data);
 
           self.resume();
+
+          // The user may have scrolled further while we were paused
+          self.scrollHandler();
         });
       });
     });

**Comment by mattsince87** [comment]
@fflewddur @fieg hey, i don't know if i'm doing something incorrect but i can't get @fflewddur's answer to work. Whenever i use a non-minified version of IAS it simply doesn't run/work (no errors in console). Would it be possible to upload a stand-alone version with paging & fast scroll working?

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
