### ISSUE TITLE
Refreshing page is loading next items

### ISSUE THREAD

**Issue by rjgamer** [webcreate/infinite-ajax-scroll#177]
Hi,

If you are scolling down to the trigger button and then refreshing the page (F5), the next items will be loading without clicking on the trigger button.

Check the behaviour on my page (language is only german, sorry):
http://free2play-games.de/games/alle-games/

Is it a bug or is it a feature? If a feature: How can I disable this behaviour?

rjgamer

**Comment by rjgamer** [comment]
* Little push *

**Comment by rjgamer** [comment]
Question posted on Stack Overflow:
https://stackoverflow.com/questions/28164376/ias-refreshing-page-is-loading-next-items

**Comment by fieg** [comment]
I will look into. I don't believe there is an option at the moment to disable that.

**Comment by memory-d** [comment]
I got this issue too.

**Comment by WR-TDW** [comment]
Dear Mr. Fieg,

the same situation, if you work without the "271173f.css". It is the same as You type the key "F5".
You have no Problem, if You not use key "F5", You go on the top command line on the end of "http://infiniteajaxscroll.com/examples/history/page2.html" and set the key "return", than You have no problems. The last not word without "271173f.css". You get a refresh and any reps.

**Comment by WR-TDW** [comment]
Dear Mr. Fieg,

if You not work with 271173f.css and start Google Chrom Version 41.0.2272.89 m, Opera Version 12.17, Safari 5.1.7  so repeats items 4 or 2 repeats for every items! Mozilla FireFox Version 36.0.1, Internet Explorer 11 have no problems.

**Comment by fieg** [comment]
The purpose of the trigger is to let visitors get to the footer eventually and not some sort of click-wall to get the rest of the pages. But perhaps I'm misunderstanding exactly what you want to achieve here. Can you elaborate some more on you use case?

ps. Sorry for the late reaction! Also I can't reproduce this any more on your website, which of course you might have already updated since you started this issue. Is the issue reproducible in any of the examples at infiniteajaxscroll.com?

**Comment by rjgamer** [comment]
Hi,

please checkout http://alt.free2play-games.de

Von meinem Windows Phone gesendet
________________________________
Von: Jeroen Fiege<mailto:notifications@github.com>
Gesendet: ‎08.‎05.‎2015 17:33
An: webcreate/infinite-ajax-scroll<mailto:infinite-ajax-scroll@noreply.github.com>
Cc: Jonathan Nessier<mailto:jonathan.nessier@outlook.com>
Betreff: Re: [infinite-ajax-scroll] Refreshing page is loading next items (#177)

The purpose of the trigger is to let visitors get to the footer eventually and not some sort of click-wall to get the rest of the pages. But perhaps I'm misunderstanding exactly what you want to achieve here. Can you elaborate some more on you use case?

ps. Sorry for the late reaction! Also I can't reproduce this any more on your website, which of course you might have already updated since you started this issue. Is the issue reproducible in any of the examples at infiniteajaxscroll.com?

---

**Comment by fieg** [comment]
Hi, I checked the link but I don't see IAS?

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and the issue should be resolved. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
