### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by fspoettel** [webcreate/infinite-ajax-scroll#194]
Would be great if this package would adhere some kind of module format to make it work in Browserify / Webpack.

**Comment by brettburwell** [comment]
+1 for this feature. I'm bumping into the same issue.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
