### ISSUE TITLE
getScrollThreshold problem with sticky footer

### ISSUE THREAD

**Issue by kainobi** [webcreate/infinite-ajax-scroll#196]
Hi! 
As far as i can see in the source code, your plugin compares the position of the last element (+ adding it´s height) with the height of the container, which is the window object.

The website I´m currently working on has a relatively large sticky footer. When the page is loaded, there are allready enough elements, so that the page is filled, but your plugin thinks there is enough space to load more because it doesn´t take the footer into account.

I tried overriding the getScrollThreshold method because I don´t want to modify the original source:

``` javascript
IAS.prototype.getScrollThreshold = function(negativeMargin) {
...
}
```

But for some reason this does not work.

Any idea how to solve this?

Nice plugin btw.

Thanks.

**Comment by fieg** [comment]
Without a real example page it's hard to solve this from my side, as there are many ways to create a sticky footer..

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and the issue should be resolved. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
