### ISSUE TITLE
Include in cdnjs

### ISSUE THREAD

**Issue by KhanMaytok** [webcreate/infinite-ajax-scroll#203]
Can you include the script in https://cdnjs.com/ ??

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being superseded by v3. 

This issue is still considered relevant for v3 so a new issue was created: #430. If you have questions, feedback or want to contribute, please comment on the new issue.
