### ISSUE TITLE
Stop updating history when prev() is called

### ISSUE THREAD

**Issue by rjgamer** [webcreate/infinite-ajax-scroll#207]
Hi,

this is my code, most important are the last four lines...

```
var ias = $.ias({
    container: 'section ul.grid',
    item: 'li',
    next: '#pagination .next',
    delay: 0,
    negativeMargin: 1000
});
ias.extension(new IASPagingExtension());
ias.extension(new IASSpinnerExtension({
    src: WB_TEMPLATE_URL + '/img/loading.gif',
    html: '<p class="text-center"><img src="{src}"/></p>'
}));
ias.extension(new IASHistoryExtension({
    prev: '#pagination .previous'
}));
ias.on('ready', function () {
    $('#pagination').hide();
    this.prev();
});
```

Check the bevaviour on my page too: 
http://www.free2play-games.de/games/t/browsergames/

If you have scrolled a bit (as example to page 3), visited a detailpage of a game and then going back, the page number is changing in the URL (History API) to the last previous loaded page. But the behaviour should work like this: Loading the previous pages in the background but not changing the URL, because the user is landing on page 3 and not page 1

Is it possible to set a param like this.prev(true) to load the previous pages without changing the URL?

Thanks

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue are filled under: #466. If you have questions, feedback or want to contribute, please comment on the new issue.
