### ISSUE TITLE
Chrome back button vs Firefox

### ISSUE THREAD

**Issue by adyz** [webcreate/infinite-ajax-scroll#226]
Hi,

First I have to say that this is an awesome plugin, I recommend this to everybody https://medium.com/p/70d8c505175d

I noticed that if I scroll to load some new pages and than click on a link and than from that link I hit the back, the page scroll back to the place I left on Firefox, but on Chrome does not:

Firefox: http://recordit.co/VAAtaZQItS
Chrome: http://recordit.co/rhbN0f6i8d

This works great with the history API, but I don't really want the URLs to change.

Any thoughts on why is this happening and how we can fix this?

Thanks, 
Adrian

**Comment by fieg** [comment]
First, thanks for recommending this plugin!

Secondly, I think both browsers just handle it differently. What happens is, that when you scroll down, you reach, for example, an scroll offset of 500. Then you navigate away, then back. When the page loads the max scroll length is less than 500 (say for example 200 because only the first page is rendered and the next page(s) aren't loaded yet).

My assumption is that Chrome says: "hey, I can't scroll to the previous scroll offset, so scroll to the max offset available and stop". Firefox seems to think: "hey, maybe some script is adding dynamic content, let's keep trying to scroll to the required offset of 500".

I don't think there is a fix for this behaviour.

**Comment by adyz** [comment]
Thanks for your answer. I hate browser inconsistency. 

Also, on Safari Mac, there is no new AJAX request on back button. The page simply is in the exact state as you left-it. This is awesome, at least for infinite scroll.
