### ISSUE TITLE
JSON response breaking AJAX 'loaded' event

### ISSUE THREAD

**Issue by Judder** [webcreate/infinite-ajax-scroll#232]
On returning a JSON response to an AJAX 'next' event request, jQuery is throwing the following error

Uncaught Error: Syntax error, unrecognized expression: {"listing":"<html code>"}

Somewhere around here

a.proxy(function(b){e=a(this.itemsContainerSelector,b).eq(0)

which I guess is to do with the itemsContainerSelector not being able to parse the JSON response

Any easy way to work around this so that we can parse the string before the itemsContainerSelector tries to parse it?

**Comment by ahmadalkaid** [comment]
Hi,

I run into the same issue, is there anything we could do here guys

**Comment by fieg** [comment]
A PR is opened recently which adds json support: https://github.com/webcreate/infinite-ajax-scroll/pull/233. 

As soon as I find some time to work on it, I'll merge it and release a new version.

**Comment by Judder** [comment]
That works pretty well for the AJAX load, and I can catch the response with

```
ias.on('loaded', function(data, items) {
    $(".products-list").append(data['listing']);
}
```

and manipulate the results, but scrolling past the second page never triggers the load event again

Any suggestions?

**Comment by fieg** [comment]
Because JSON is returned the plugin can not detect the next url anymore (normally it looks up the next link selector). So you would have to manually set the next url. I believe it would be something like this:

1) store the next url in the `loadsd` event
2) set the `nextUrl` on the IAS instance in the `rendered` event

**Comment by mralessio** [comment]
Having json support would be really great. 

I'm trying also to catch the json response from loaded event, but getting the same error. @Judder , did you manage it in any way?

I've tested what proposed in PR 223 , what I could is to load the items once. In order to load the next items I have to trigger a load event manually. But the general logic of the plugin is not working.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.

**Comment by sabat24** [comment]
What should I return from server when I use `json` response? I tried to return an array of html strings like '<div class="item">something</div>'
but I receive an error:

```
TypeError: Node.appendChild: Argument 1 is not an object.infinite-ajax-scroll.es.js:617
    appendFn infinite-ajax-scroll.es.js:617TypeError: Node.appendChild: Argument 1 is not an object.infinite-ajax-scroll.es.js:617
    appendFn infinite-ajax-scroll.es.js:617
```

I know that class wanted to append a DOM object, but how can I serve such object from server? Should I parse it somewhere?

**Comment by fieg** [comment]
Hi @sabat24, I created an example for JSON:
https://infiniteajaxscroll.com/examples/json/
(edit in codesandbox to see inner workings)

I would love to hear if this clarifies things for you.

**Comment by sabat24** [comment]
Thank you for that example. Now everything is very clear and much simpler to implement for me.
