### ISSUE TITLE
Paging Extension callbacks, pageChange and rendered 

### ISSUE THREAD

**Issue by samburgers** [webcreate/infinite-ajax-scroll#238]
Hi, 

Thanks for the excellent plugin. I am attempting to use it to create a infinite loading of single articles. What i need to do is load and render the new article content well before the user reaches the bottom of the page, and then trigger the "pageChange" event only when the next article comes into view (so we can update the page URL and fire tracking events etc).

Much like articles on bloomberg, digiday etc etc.

Using the "Paging Extension" and "History Extension" I can get really really close to what it needs to do, but not quite.

What would be useful is a new option to declare the scroll offset to render the next page, which is decoupled from the scroll offset setting that triggers the "pageChange" event.

It would also be exceptional if we could have access to the page title meta in the "pageChange" callback, so we can update the TITLE in the browser tab:

```
$ias.on('pageChange', function(pageNum, scrollOffset, url, pageTitle) {

  //update page title etc.

}
```

I hope that all makes sense!

Many thanks

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. Other suggestions are still considered relevant for v3 and are filled under: #428. If you have questions, feedback or want to contribute, please comment on the new issue.
