### ISSUE TITLE
Infinite Scrolling upwards Feature request

### ISSUE THREAD

**Issue by rsambhangi** [webcreate/infinite-ajax-scroll#274]
Really like the plugin with ease of integration to enable infinite scrolling for existing paginated pages.

Would like to have infinite scrolling upwards(to avoid loading previous item on button click). 
Any one tried to work on this feature?

On a separate note, there is a bug with browser back button when navigating between listing and details page. #273 

Willing to buy the commercial license once this feature request and #273  are addressed.

Thanks in advance!

**Comment by amdad** [comment]
YES! This is probably only thing is was missing searching when checking docs and demo. @fieg will this feature be added? Pleeease. :) I think this should be rather simple thing to add since you have solution working already. Just add opposite direction ;)  

Thanks for great plugin.

**Comment by fieg** [comment]
Hi there! Thank you for reporting this. I have worked on this feature in the past, but as easy as it seems, it has some drawbacks. 

Because items would be inserted at the top, the new items are always in view and would trigger a new load, resulting in a continuous loading of previous pages until page 1 is reached. User experience wise this is not something you want for your users if you ask me.

**Comment by Nuranto** [comment]
@fieg 
Could be done with a button  ? ( "Load previous" button )
It's not perfect, but can solve the issue while someone find a better solution...

**Comment by fieg** [comment]
Yes, this is the method v2 used. I am researching a better way, but if I can’t find a better way, then I will implement it like this.

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue are filled under: #466. If you have questions, feedback or want to contribute, please comment on the new issue.
