### ISSUE TITLE
Noneleft text appending to non infinite scrolling blocks

### ISSUE THREAD

**Issue by lcecchetti** [webcreate/infinite-ajax-scroll#277]
The way used to retrieve items is not coherent along the code.

This
`$(this.itemSelector, this.getItemsContainer().get(0))`
is different from this
`$itemContainer.find(this.itemSelector)`

The first one will search in the whole document if no parent container is found.
The second one will return undefined in the same case.

This will lead for example to have the noneleft text appended even in cases where infinite scrolling is not supposed to be active.

The quick fix would be to update the first method, used for example in getFirstItem and getLastItem functions, this way:

`$(this.itemSelector, this.itemsContainerSelector)`

But maybe i'm missing the point of using the current way.

**Comment by fieg** [comment]
Hi lcecchetti, thank you for this. I will certainly look into this. 

Might be related to #279.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
