### ISSUE TITLE
Update TITLE on scroll

### ISSUE THREAD

**Issue by luccin** [webcreate/infinite-ajax-scroll#278]
Hey!
Is there any possibility to get the TITLE in the head to get updated when scrolling?

Thanks for a great script.

**Comment by fieg** [comment]
I looked into it and this is currently not possible, but it's indeed a very nice feature. Will implement when I find some time to do so.

**Comment by uru** [comment]
@fieg Is it possible to add this feature?

**Comment by JuanDBB** [comment]
Hello, any update on this or how can be done? It's really a problem if the url changes but the title doesn't.

**Comment by fieg** [comment]
Hi @JuanDBB, thanks for taking the time to reply. 

I'm currently working on v3 of IAS. This new version _will_ support this. You can sign up here to get an update when it's ready: https://v3.infiniteajaxscroll.com

**Comment by JuanDBB** [comment]
Thank you very much @fieg

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented, see for e.g. https://infiniteajaxscroll.com/examples/articles/ (title is updated on page scroll). If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
