### ISSUE TITLE
Duplicate content on scroll - urgent help please

### ISSUE THREAD

**Issue by p-drolima** [webcreate/infinite-ajax-scroll#281]
Hi,

Content is duplicating on second page to 3rd. PHP implementation

Thank you

**Comment by fieg** [comment]
This is probably to some misconfiguration when implementing IAS. Please visit http://infiniteajaxscroll.com/docs/ for documentation or you can ask you question on [stackoverflow](http://stackoverflow.com/questions/ask?tags=jquery-ias).

If you strongly believe this is due to a bug in Infinite AJAX Scroll, please comment on this issue with more details.
