### ISSUE TITLE
Issue with the back button

### ISSUE THREAD

**Issue by microdesign** [webcreate/infinite-ajax-scroll#320]
Yes there is a problem with the back button 

Please go to this page
https://www.naken.co.uk/lighting/hanging-lights

- Load more products 
- Click on some of the new loaded products 
- from the product details page press back button 
- your plugin load only the last page at the top 

the 1 page is missing from the loaded.

**Comment by fieg** [comment]
Do you have the history extension enabled? Because I don't see the url updating when scrolling. It's required for the back button to work properly.

**Comment by microdesign** [comment]
I remove the history because of page jump around when the user press back button.

**Comment by lear2000** [comment]
I have the exact same issue, I see you added a anchor. Can you elaborate on how you did that?

**Comment by fieg** [comment]
I'm closing this issue because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue are filled under: #466. If you have questions, feedback or want to contribute, please comment on the new issue.
