### ISSUE TITLE
Infinite offset for the Trigger extension

### ISSUE THREAD

**Issue by lsarni** [webcreate/infinite-ajax-scroll#321]
I had to add the Trigger extension to use the History extension, but I don't really want to show the "Load more items" link at the end of each page.

Now I just used a big offset, but it would be a good idea to have a value that means "never show this link" as in an infinite offset. Maybe `-1`?

ias.extension(new IASTriggerExtension(
   offset: -1
));

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
