### ISSUE TITLE
`IASTriggerExtension`  count need to reset after `jQuery.ias().reinitialize()`

### ISSUE THREAD

**Issue by Akshay-Hegde** [webcreate/infinite-ajax-scroll#322]
Is there any way to reset `IASTriggerExtension` count after `jQuery.ias().reinitialize()` ?

Example : say offset : 10, initially 8 items loaded, next user performs search/filter new items will render after `jQuery.ias().reinitialize()` that time `Load More Items` should not come. it should reset counter with 0, since its `reinitialize()`

**Comment by fieg** [comment]
I think this is handled in #316, but it's not officially released yet. Can you test it by using the source (master branch)? 

If it works I'll release a new version.

**Comment by Akshay-Hegde** [comment]
@fieg Thank you, I tested,  its working fine, also its resetting count too.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3. If you have questions, feedback or think this issue was closed by mistake, please comment on this issue.
