### ISSUE TITLE
InfiniteAjaxScroll appends random ID on my `next` url and persistent href from previous state?

### ISSUE THREAD

**Issue by ivanasetiawan** [webcreate/infinite-ajax-scroll#395]
**Support question**
(1) I am using InfiniteAjaxScroll v3 and figured out that when I am initialising it the `next` URL got modified and added with a random ID. I saw it on the official example and the random ID also got added. How can I remove this?
Example: `<a class="next" href="http://abc.com:8000/browse/?page=2&page=3&page=4&page=5">Dummy next pagination</a>`

But on the network tab I see `http://abc.com:8000/browse/?page=2&1573396662371&page=3&1573396663965&page=4&1573396807373&page=5`
I have no idea why `1573396662371`, `1573396662371`, and `1573396807373` got added and how to clean those IDs?

(2) On my page, there's a `select` element and the idea is to reinitialise `InfiniteAjaxScroll` when there's a change on the `select`, however even after I `unbind` and `reinitialize`, the `Start loading` URL seems to load the old state (memorized old data). How can I solve this?

**Environment**

- Infinite Ajax Scroll version: 3
- Browser version: FF Dev 71.0b5 (64-bit)
- Operating System: Mac OS Catalina

**Comment by fieg** [comment]
A timestamp is added to the url to prevent caching. See https://github.com/webcreate/infinite-ajax-scroll/blob/master/src/infinite-ajax-scroll.js#L153

I understand that this isn't something you would always want. It's on my roadmap to change/improve this behavior.

**Comment by fabiocaccamo** [comment]
@fieg thank you for this great library.
I have a similar problem, my backend systema generates the next page url using the current query string and replacing the page number value. After multiple scrolls my url looks like: `?p=7&1590774588692=&1590774590771=&1590774593008=&1590774595796=&1590774598283=` because the timestamp results as a different key to the query-string parser.
It would be nice to have a simple option to don't append the timestamp to the requested url.

**Comment by fieg** [comment]
Hi @fabiocaccamo, Thanks for bring this to my attention. I'm aware of the issue and am tracking everything related to this in issue #457.
