### ISSUE TITLE
browser freezes when appending (a lot of) new elements to DOM

### ISSUE THREAD

**Issue by bfanelli** [webcreate/infinite-ajax-scroll#69]
feature request:

when scrolling and a new page is retrieved and inserted into the DOM, the browser - including the scrollbar itself - freezes.  probably related to how the new items are inserted.

see these links for more info:
https://developers.google.com/speed/articles/javascript-dom
http://jsfiddle.net/dmethvin/cbEEW/2/
http://forum.jquery.com/topic/jquery-optimize-large-dom-inserts

thanks.

**Comment by fieg** [comment]
This issue is closed because Infinite Ajax Scroll 2 [reached end of life](https://infiniteajaxscroll.com/blog/end-of-life-ias2/) and is being [superseded by v3](https://infiniteajaxscroll.com).

Suggestions given in this issue were taken into account when working on v3 and some are even implemented. If you have questions, feedback or think this issue is closed by mistake, please comment on this issue.
